import { expect, test } from '@playwright/test'
test('filtra, pagina y abre detalle de cierres', async ({ page }) => {
  page.on('console', (message) => { if (message.type() === 'error') console.log('Browser error:', message.text()) })
  page.on('pageerror', (error) => console.log('Page error:', error.message))
  const email = process.env['E2E_EMAIL'], password = process.env['E2E_PASSWORD']
  test.skip(!email || !password, 'Requiere credenciales locales')
  await page.goto('/login')
  await page.getByLabel('Email').fill(email!)
  await page.getByLabel('Contrasena').fill(password!)
  await page.getByRole('button', { name: 'Ingresar' }).click()
  await expect(page).toHaveURL(/\/pos$/)
  await page.goto('/caja/historial')
  await expect(page.getByRole('heading', { name: 'Historial de caja', exact: true })).toBeVisible()
  await page.getByLabel('Desde', { exact: true }).fill('2026-07-01')
  await page.getByLabel('Hasta', { exact: true }).fill('2026-09-30')
  await page.getByRole('button', { name: 'Aplicar filtros' }).click()
  await expect(page.getByText(/20 de \d+ días/)).toBeVisible()
  await page.screenshot({ path: '/tmp/cash-history-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Siguiente', exact: true }).click()
  await expect(page.getByText(/Página 2 de \d+/)).toBeVisible()
  await page.getByRole('button', { name: 'Ver turnos', exact: true }).first().click()
  await expect(page.getByRole('button', { name: 'Volver al resumen', exact: true })).toBeVisible()
  await expect(page.getByText(/20 de \d+ días/)).not.toBeVisible()
  await expect(page.locator('dt:visible').filter({ hasText: /^Apertura$/ }).first()).toBeVisible()
  await expect(page.locator('dt:visible').filter({ hasText: /^Cierre$/ }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Ver detalle' }).first().click()
  const dialog = page.getByRole('dialog', { name: 'Detalle del turno' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('heading', { name: 'Ingresos y gastos del turno', exact: true })).toBeVisible()
  await expect(dialog.getByText('Responsable del cierre', { exact: true })).toBeVisible()
  await expect(dialog.getByText('admin@moveon.local', { exact: true })).toBeVisible()
  await expect(dialog.getByText('Sin ventas registradas en este turno')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: 'Volver al resumen', exact: true }).click()
  await expect(page.getByText(/Página 2 de \d+/)).toBeVisible()
  await page.getByLabel('Desde', { exact: true }).fill('2026-09-13')
  await page.getByLabel('Hasta', { exact: true }).fill('2026-09-13')
  await page.getByRole('button', { name: 'Aplicar filtros' }).click()
  await expect(page.getByText('1 de 1 días')).toBeVisible()
  await page.getByRole('button', { name: 'Ver turnos', exact: true }).click()
  await expect(page.getByText('3 de 3 turnos')).toBeVisible()
  await page.getByRole('button', { name: 'Volver al resumen', exact: true }).click()
  await page.getByLabel('Desde', { exact: true }).fill('2026-09-14')
  await page.getByLabel('Hasta', { exact: true }).fill('2026-09-14')
  await page.getByRole('button', { name: 'Aplicar filtros' }).click()
  await expect(page.getByText('1 de 1 días')).toBeVisible()
  await page.getByRole('button', { name: 'Ver turnos', exact: true }).click()
  await expect(page.getByText('2 de 2 turnos')).toBeVisible()
  await page.getByRole('button', { name: 'Ver detalle' }).first().click()
  await expect(dialog.getByText('SEED-HIST-001', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: /SEED-HIST-001/ }).click()
  await expect(dialog.getByText('Proteína de prueba historial', { exact: true })).toBeVisible()
  await expect(dialog.getByText('Ref. SEED-TRANSFER-001', { exact: true })).toBeVisible()
  await expect(dialog.getByText('Motivo de anulación: Registro duplicado de prueba', { exact: true })).toBeVisible()
  await page.screenshot({ path: '/tmp/cash-history-detail-desktop.png' })
  const download = page.waitForEvent('download')
  await dialog.getByRole('button', { name: 'Descargar Excel del turno' }).click()
  expect((await download).suggestedFilename()).toMatch(/\.xlsx$/)
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByText('2 de 2 turnos')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/tmp/cash-history-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Ver detalle' }).first().click()
  await expect(dialog).toBeVisible()
  await page.screenshot({ path: '/tmp/cash-history-detail-mobile.png' })
  await dialog.getByRole('button', { name: 'Cerrar detalle', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('dt:visible').filter({ hasText: /^Apertura$/ }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Volver al resumen', exact: true }).click()
  await page.getByLabel('Responsable', { exact: true }).selectOption({ label: 'admin@moveon.local' })
  await page.getByLabel('Estado del cuadre', { exact: true }).selectOption({ label: 'Con diferencia' })
  await page.getByRole('button', { name: 'Aplicar filtros' }).click()
  await expect(page.getByText('1 de 1 días')).toBeVisible()
  await page.getByRole('button', { name: 'Ver turnos', exact: true }).click()
  await expect(page.getByText('1 de 1 turnos')).toBeVisible()
  await page.getByRole('button', { name: 'Volver al resumen', exact: true }).click()
  await page.getByLabel('Estado del cuadre', { exact: true }).selectOption({ label: 'Cuadrados' })
  await page.getByRole('button', { name: 'Aplicar filtros' }).click()
  await expect(page.getByText('1 de 1 días')).toBeVisible()
  await page.getByRole('button', { name: 'Ver turnos', exact: true }).click()
  await expect(page.getByText('1 de 1 turnos')).toBeVisible()
})
